# Generated by Django 5.0 on 2024-07-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="bill_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="end_bill_no",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="start_bill_no",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="creditlockbill",
            name="party",
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name="PushedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_code", models.TextField(max_length=30)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="app.billing",
                    ),
                ),
            ],
        ),
    ]
