# Generated by Django 5.0 on 2024-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_billing_bill_count_billing_end_bill_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billstatistics",
            name="count",
            field=models.TextField(max_length=30),
        ),
    ]
