# Generated by Django 5.0 on 2024-07-30 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_creditlockbill_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_no",
                    models.TextField(max_length=60, primary_key=True, serialize=False),
                ),
                ("party", models.TextField(max_length=50)),
                ("salesman", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.TextField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("allocated", models.IntegerField()),
                ("rate", models.FloatField()),
                ("reason", models.TextField(max_length=50)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.orders"
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "product")},
            },
        ),
    ]
