# Generated by Django 5.0 on 2024-07-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_orders_orderproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="creditlock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.creditlockbill",
            ),
        ),
    ]
