# Generated by Django 5.0 on 2024-07-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_orders_creditlock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="app.orders",
            ),
        ),
    ]
