# Generated by Django 5.0 on 2024-07-30 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_orderproducts_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="date",
            field=models.DateField(default=datetime.date(2024, 7, 30)),
            preserve_default=False,
        ),
    ]
