# Generated by Django 5.0 on 2024-07-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_orders_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlockbill",
            name="billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditlocks",
                to="app.billing",
            ),
        ),
    ]
