# Generated by Django 5.0 on 2024-07-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_creditlockbill_billing"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CreditLockBill",
            new_name="CreditLock",
        ),
    ]
