# Generated by Django 5.2 on 2025-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_delete_barcode_barcodemap_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="party_hul_code",
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
