# Generated by Django 5.0 on 2024-07-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_creditlockbill_creditlock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name": "Orders", "verbose_name_plural": "Orders"},
        ),
        migrations.AddField(
            model_name="orders",
            name="billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="app.billing",
            ),
        ),
    ]
