# Generated by Django 5.0 on 2024-07-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_orders_options_orders_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[("SH", "Shikhar"), ("SE", "Salesman")],
                max_length=15,
                null=True,
            ),
        ),
    ]
