# Generated by Django 5.0 on 2024-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_orders_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("idx", models.IntegerField()),
                ("ref", models.TextField(max_length=200)),
                ("desc", models.TextField(max_length=200)),
                ("amt", models.IntegerField()),
                ("bank", models.TextField(max_length=20)),
            ],
        ),
    ]
