# Generated by Django 5.0 on 2024-09-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_bank"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bank",
            unique_together={("date", "idx")},
        ),
    ]
