# Generated by Django 5.0 on 2024-09-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_bank_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("master_code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "type",
                    models.CharField(db_default=models.Value("shop"), max_length=10),
                ),
                ("addr", models.CharField(blank=True, max_length=150, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name_plural": "Party",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                ("discount", models.FloatField(db_default=models.Value(0), default=0)),
                ("roundoff", models.FloatField(db_default=models.Value(0), default=0)),
                (
                    "type",
                    models.CharField(
                        db_default=models.Value("sales"), max_length=15, null=True
                    ),
                ),
                ("tds", models.FloatField(db_default=models.Value(0), default=0)),
                ("tcs", models.FloatField(db_default=models.Value(0), default=0)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("mode", models.CharField(max_length=30)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.sales",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Collection",
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amt", models.FloatField(null=True)),
                ("inum", models.CharField(max_length=20)),
                ("adj_amt", models.FloatField(default=0)),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
                (
                    "from_bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adjusted_from",
                        to="app.sales",
                    ),
                ),
                (
                    "to_bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="adjusted_to",
                        to="app.sales",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Adjustment",
                "unique_together": {("inum", "from_bill", "to_bill")},
            },
        ),
    ]
