# Generated by Django 5.0 on 2024-09-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_party_sales_collection_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningBalance",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("amt", models.FloatField(blank=True, null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.party"
                    ),
                ),
            ],
        ),
    ]
