# Generated by Django 5.0 on 2024-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_openingbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beat",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=40)),
                ("salesman_id", models.IntegerField()),
                ("salesman_code", models.IntegerField()),
                ("salesman_name", models.IntegerField()),
                ("days", models.TextField(max_length=40)),
                ("plg", models.TextField(max_length=15)),
            ],
        ),
    ]
