# Generated by Django 5.0 on 2024-09-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_openingbalance_beat_party_beat_sales_beat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="party",
            name="beat",
        ),
    ]
