# Generated by Django 5.0 on 2024-09-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_remove_party_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creditlock",
            name="delete",
            field=models.BooleanField(db_default=models.Value(False), default=False),
        ),
        migrations.AlterField(
            model_name="sales",
            name="beat",
            field=models.TextField(max_length=40, null=True),
        ),
    ]
