# Generated by Django 5.0 on 2024-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_beatmapping_creditlock_delete_alter_sales_beat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BeatMapping",
        ),
        migrations.AddField(
            model_name="orders",
            name="beat",
            field=models.TextField(default="a", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="delete",
            field=models.BooleanField(db_default=models.Value(False), default=False),
        ),
        migrations.AddField(
            model_name="orders",
            name="releaselock",
            field=models.BooleanField(db_default=models.Value(False), default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="creditlock",
            field=models.BooleanField(db_default=models.Value(False), default=False),
        ),
    ]
