# Generated by Django 5.0 on 2024-09-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_delete_beatmapping_orders_beat_orders_delete_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditLock",
        ),
    ]
