# Generated by Django 5.0 on 2024-09-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_delete_creditlock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processstatus",
            name="billing",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="billing",
        ),
        migrations.DeleteModel(
            name="PushedCollection",
        ),
        migrations.DeleteModel(
            name="Billing",
        ),
    ]
