# Generated by Django 5.0 on 2024-09-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_remove_processstatus_billing_remove_orders_billing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.IntegerField()),
                ("error", models.TextField(blank=True, max_length=100000, null=True)),
                (
                    "start_bill_no",
                    models.TextField(blank=True, max_length=10, null=True),
                ),
                ("end_bill_no", models.TextField(blank=True, max_length=10, null=True)),
                ("bill_count", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="app.billing",
            ),
        ),
        migrations.AddField(
            model_name="processstatus",
            name="billing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_status",
                to="app.billing",
            ),
        ),
        migrations.CreateModel(
            name="PushedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_code", models.TextField(max_length=30)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="app.billing",
                    ),
                ),
            ],
        ),
    ]
