# Generated by Django 5.0 on 2024-09-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_billing_orders_billing_processstatus_billing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="beat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="app.beat",
            ),
        ),
    ]
