# Generated by Django 5.0 on 2024-09-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_orders_beat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="app.party",
            ),
        ),
    ]
