# Generated by Django 5.0 on 2024-09-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_orders_party"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="releaselock",
            new_name="release",
        ),
    ]
