# Generated by Django 5.0 on 2024-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_rename_releaselock_orders_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="value",
            field=models.FloatField(db_default=models.Value(0), default=0),
        ),
    ]
