# Generated by Django 5.0 on 2024-09-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_orders_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="value",
        ),
    ]
