# Generated by Django 5.0 on 2024-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_outstanding"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="hul_code",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
