# Generated by Django 5.0 on 2024-09-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_party_hul_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="place_order",
            field=models.BooleanField(db_default=models.Value(False), default=False),
        ),
    ]
