# Generated by Django 5.0 on 2024-09-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_orders_place_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
