# Generated by Django 5.0 on 2024-09-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_mymodel"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bank",
            unique_together={("date", "idx", "bank")},
        ),
    ]
