# Generated by Django 5.0 on 2024-09-16 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_bank_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.sales",
                    ),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="collection",
                        to="app.bank",
                    ),
                ),
            ],
        ),
    ]
