# Generated by Django 5.0 on 2024-09-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_bankcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcollection",
            name="amt",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankcollection",
            name="entry_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankcollection",
            name="bill",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.outstanding",
            ),
        ),
    ]
