# Generated by Django 5.0 on 2024-09-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_bankcollection_amt_bankcollection_entry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("cheque", "Cheque"),
                    ("neft", "NEFT"),
                    ("cash", "Cash Deposit"),
                    ("others", "Others"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bankcollection",
            name="entry_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
