# Generated by Django 5.0 on 2024-09-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_bank_pushed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcollection",
            name="coll_code",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
