# Generated by Django 5.0 on 2024-09-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_bankcollection_coll_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankcollection",
            unique_together={("bill", "cheque")},
        ),
    ]
