# Generated by Django 5.0 on 2024-09-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_alter_bank_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sync",
            fields=[
                (
                    "process",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
