# Generated by Django 5.0 on 2024-09-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_sync_delete_mymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="type",
            field=models.TextField(
                choices=[
                    ("cheque", "Cheque"),
                    ("neft", "NEFT"),
                    ("cash", "Cash Deposit"),
                    ("others", "Others"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
