# Generated by Django 5.0 on 2024-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_alter_bank_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="id",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
