# Generated by Django 5.1.1 on 2024-10-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_alter_bank_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"verbose_name_plural": "Bank"},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name": "Orders", "verbose_name_plural": "Billing"},
        ),
        migrations.AlterModelOptions(
            name="outstanding",
            options={"managed": False, "verbose_name_plural": "Outstanding"},
        ),
        migrations.AddField(
            model_name="orders",
            name="partial",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="bank",
            name="pushed",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="creditlock",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="delete",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="place_order",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="release",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="party",
            name="type",
            field=models.CharField(db_default="shop", max_length=10),
        ),
        migrations.AlterField(
            model_name="sales",
            name="discount",
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="sales",
            name="roundoff",
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="sales",
            name="tcs",
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="sales",
            name="tds",
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="sales",
            name="type",
            field=models.CharField(db_default="sales", max_length=15, null=True),
        ),
    ]
