# Generated by Django 5.1.1 on 2024-10-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_alter_bank_options_alter_orders_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersProxy",
            fields=[],
            options={
                "verbose_name": "order",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.orders",),
        ),
        migrations.RemoveField(
            model_name="orders",
            name="partial",
        ),
    ]
