# Generated by Django 5.1.1 on 2024-10-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_ordersproxy_remove_orders_partial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproducts",
            name="billed",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
