# Generated by Django 5.1.1 on 2024-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_orderproducts_billed"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="force_order",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
