# Generated by Django 5.1.1 on 2024-10-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_orders_force_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproducts",
            name="billed",
        ),
    ]
