# Generated by Django 5.1.1 on 2024-10-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_alter_orderproducts_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="beat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="app.beat",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="app.party",
            ),
        ),
    ]
