# Generated by Django 5.1.1 on 2024-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_orders_beat_alter_orders_party"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutstandingRaw",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("amt", models.FloatField(blank=True, null=True)),
                ("beat", models.TextField(max_length=40)),
                ("date", models.DateField()),
            ],
            options={
                "managed": False,
            },
        ),
    ]
