# Generated by Django 5.1.1 on 2024-10-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_outstandingraw"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OutstandingRaw",
        ),
    ]
