# Generated by Django 5.1.1 on 2024-10-09 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_delete_outstandingraw"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesmanCollection",
            fields=[
                (
                    "id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("amt", models.IntegerField()),
                (
                    "type",
                    models.TextField(
                        choices=[("cheque", "Cheque"), ("neft", "NEFT")],
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesmanCollectionBill",
            fields=[
                (
                    "id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("amt", models.IntegerField()),
                (
                    "chq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="app.salesmancollection",
                    ),
                ),
                (
                    "inum",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.sales",
                    ),
                ),
            ],
        ),
    ]
