# Generated by Django 5.1.1 on 2024-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_salesmancollection_salesman"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesmancollection",
            name="time",
            field=models.DateTimeField(null=True),
        ),
    ]
