# Generated by Django 5.1.1 on 2024-10-09 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_salesmancollection_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Print",
            fields=[
                (
                    "bill",
                    models.OneToOneField(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="app.sales",
                    ),
                ),
                ("time", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("first_copy", "first_copy"),
                            ("loading_sheet", "loading_sheet"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
