# Generated by Django 5.1.1 on 2024-10-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_alter_print_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="print",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("first_copy", "First Copy"),
                    ("loading_sheet", "Loading Sheet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
