# Generated by Django 5.1.1 on 2024-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_alter_orders_beat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beat",
            name="salesman_name",
            field=models.TextField(max_length=40),
        ),
    ]
