# Generated by Django 5.0 on 2024-10-16 01:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_alter_beat_salesman_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="date",
            field=models.DateField(default=datetime.date(2024, 4, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="billing",
            name="bill_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="beat",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                default=-1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="app.beat",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="party",
            field=models.ForeignKey(
                default="unknown - manual migration",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="app.party",
            ),
            preserve_default=False,
        ),
    ]
