# Generated by Django 5.0 on 2024-10-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_billing_date_alter_billing_bill_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustment",
            name="from_bill",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="adjusted_from",
                to="app.sales",
            ),
        ),
    ]
