# Generated by Django 5.0 on 2024-10-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_alter_adjustment_from_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Einvoice",
            fields=[
                (
                    "bill",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="einvoice",
                        serialize=False,
                        to="app.sales",
                    ),
                ),
                ("irn", models.TextField()),
                ("qrcode", models.TextField()),
                ("date", models.DateField()),
                ("json", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="sales",
            name="irn",
        ),
    ]
