# Generated by Django 5.1.1 on 2024-10-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_processstatu1s_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProcessStatu1s",
            new_name="ProcessStatus",
        ),
    ]
