# Generated by Django 5.1.1 on 2024-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_rename_processstatu1s_processstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processstatus",
            name="type",
            field=models.TextField(max_length=30),
        ),
    ]
