# Generated by Django 5.1.1 on 2024-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_basepackprocessstatus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='delivered',
            field=models.BooleanField(default=True),
        ),
    ]
