# Generated by Django 5.1.1 on 2024-10-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_sales_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='delivered',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
