# Generated by Django 5.1.1 on 2024-10-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_sales_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
