# Generated by Django 5.1.1 on 2024-10-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_print_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RetailPrint',
            fields=[
            ],
            options={
                'verbose_name': 'Retail Print',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.print',),
        ),
        migrations.CreateModel(
            name='WholeSalePrint',
            fields=[
            ],
            options={
                'verbose_name': 'WholeSale Print',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.print',),
        ),
        migrations.CreateModel(
            name='Eway',
            fields=[
                ('bill', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='eway', serialize=False, to='app.sales')),
                ('ewb_no', models.TextField()),
                ('time', models.DateTimeField()),
                ('vehicle', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='app.vehicle')),
            ],
        ),
    ]
