# Generated by Django 5.1.1 on 2024-10-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_vehicle_retailprint_wholesaleprint_eway'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSheet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.beat',),
        ),
        migrations.AlterField(
            model_name='eway',
            name='ewb_no',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eway',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eway',
            name='vehicle',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='app.vehicle'),
        ),
    ]
