# Generated by Django 5.1.1 on 2024-10-28 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_pendingsheet_alter_eway_ewb_no_alter_eway_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanLoadingSheet',
            fields=[
                ('inum', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('salesman', models.TextField(max_length=30)),
                ('party', models.TextField(blank=True, max_length=30, null=True)),
                ('beat', models.TextField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PendingSheet',
        ),
        migrations.CreateModel(
            name='SalesmanPendingSheet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.beat',),
        ),
        migrations.RenameField(
            model_name='print',
            old_name='time',
            new_name='print_time',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='type',
            new_name='print_type',
        ),
        migrations.AddField(
            model_name='print',
            name='irn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='app.vehicle'),
        ),
        migrations.AddField(
            model_name='print',
            name='loading_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills', to='app.salesmanloadingsheet'),
        ),
        migrations.DeleteModel(
            name='Einvoice',
        ),
        migrations.DeleteModel(
            name='Eway',
        ),
    ]
