# Generated by Django 5.1.1 on 2024-10-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_rename_print_bill_delete_retailprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPrint',
            fields=[
            ],
            options={
                'verbose_name': 'Retail Print',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.bill',),
        ),
        migrations.CreateModel(
            name='WholeSalePrint',
            fields=[
            ],
            options={
                'verbose_name': 'WholeSale Print',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.bill',),
        ),
    ]
