# Generated by Django 5.1.1 on 2024-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_vehicle_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='time',
        ),
        migrations.AddField(
            model_name='bill',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
