# Generated by Django 5.1.1 on 2024-10-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_bill_loading_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDelivery',
            fields=[
            ],
            options={
                'verbose_name': 'Bill Delivery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.bill',),
        ),
        migrations.AddField(
            model_name='bill',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
