# Generated by Django 5.0 on 2024-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0087_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.CharField(max_length=30),
        ),
    ]
