# Generated by Django 5.0 on 2024-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0088_alter_settings_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
