# Generated by Django 5.0 on 2024-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_settings_status_alter_settings_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="plain_loading_sheet",
            field=models.BooleanField(default=False),
        ),
    ]
