# Generated by Django 5.1.1 on 2024-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0090_bill_plain_loading_sheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodayBillOut",
            fields=[],
            options={
                "verbose_name": "Today Bill Out",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.vehicle",),
        ),
        migrations.AlterField(
            model_name="bill",
            name="plain_loading_sheet",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
