# Generated by Django 5.1.1 on 2024-11-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_todaybillout_alter_bill_plain_loading_sheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodayBillIn",
            fields=[],
            options={
                "verbose_name": "Today Bill In",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app.vehicle",),
        ),
    ]
