# Generated by Django 5.1.1 on 2024-11-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_bill_cash_bill_bill_is_reloaded"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankcollection",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="bankcollection",
            name="cheque",
        ),
        migrations.DeleteModel(
            name="Bank",
        ),
    ]
