# Generated by Django 5.1.1 on 2024-11-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_alter_bankcollection_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankCollection",
        ),
    ]
