# Generated by Django 5.1.1 on 2024-11-26 00:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_delete_bankcollection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChequeDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("SBI", "State Bank of India"),
                            ("KVB", "Karur Vysya Bank"),
                            ("HDFC", "HDFC Bank"),
                            ("ICICI", "ICICI Bank"),
                            ("IB", "Indian Bank"),
                            ("PNB", "Punjab National Bank"),
                            ("BOB", "Bank of Baroda"),
                            ("UBI", "Union Bank of India"),
                            ("CANARA", "Canara Bank"),
                            ("AXIS", "Axis Bank"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cheque_no", models.CharField(max_length=20)),
                ("amt", models.FloatField()),
                ("date", models.DateField(default=datetime.date(2024, 11, 26))),
                (
                    "party",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChequeCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amt", models.IntegerField()),
                ("entry_date", models.DateField(auto_now_add=True)),
                ("coll_code", models.TextField(blank=True, max_length=30, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.outstanding",
                    ),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="collection",
                        to="app.chequedeposit",
                    ),
                ),
            ],
            options={
                "unique_together": {("bill", "cheque")},
            },
        ),
    ]
