# Generated by Django 5.1.1 on 2024-11-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_chequedeposit_chequecollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chequedeposit",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
