# Generated by Django 5.1.1 on 2024-11-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0097_alter_chequedeposit_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chequedeposit",
            name="party",
        ),
    ]
