# Generated by Django 5.1.1 on 2024-11-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0099_chequedeposit_party"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                ("date", models.DateField()),
                ("idx", models.IntegerField()),
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("ref", models.TextField(max_length=200)),
                ("desc", models.TextField(max_length=200)),
                ("amt", models.IntegerField()),
                ("bank", models.TextField(max_length=20)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("neft", "NEFT"),
                            ("cash", "Cash Deposit"),
                            ("others", "Others"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("pushed", models.BooleanField(db_default=False, default=False)),
                (
                    "matched_cheque",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matched_bank",
                        to="app.chequedeposit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bank",
                "unique_together": {("date", "idx", "bank")},
            },
        ),
    ]
