# Generated by Django 5.1.1 on 2024-11-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0105_rename_chequecollection_bankcollection_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankstatement",
            name="pushed",
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="type",
            field=models.TextField(
                choices=[
                    ("cheque", "Cheque"),
                    ("neft", "NEFT"),
                    ("upi", "UPI (IKEA)"),
                    ("cash", "Cash Deposit"),
                    ("others", "Others"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
