# Generated by Django 5.1.1 on 2024-11-26 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0106_remove_bankstatement_pushed_alter_bankstatement_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chequedeposit",
            old_name="date",
            new_name="entry_date",
        ),
        migrations.RemoveField(
            model_name="bankcollection",
            name="entry_date",
        ),
        migrations.AddField(
            model_name="bankcollection",
            name="pushed",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="chequedeposit",
            name="cheque_date",
            field=models.DateField(default=datetime.date(2024, 11, 26)),
            preserve_default=False,
        ),
    ]
