# Generated by Django 5.1.1 on 2024-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0107_rename_date_chequedeposit_entry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chequedeposit",
            name="deposit_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
