# Generated by Django 5.1.1 on 2024-11-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0108_chequedeposit_deposit_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcollection",
            name="coll_code",
        ),
        migrations.AddField(
            model_name="collection",
            name="bank_entry",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ikea_collection",
                to="app.bankstatement",
            ),
        ),
    ]
