# Generated by Django 5.1.1 on 2024-11-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0111_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
