# Generated by Django 5.1.1 on 2024-11-30 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0112_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmancollection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="salesmancollection",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 11, 30, 13, 9, 15, 134550),
            ),
            preserve_default=False,
        ),
    ]
