# Generated by Django 5.1.1 on 2024-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0113_alter_salesmancollection_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmancollection",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
