# Generated by Django 5.1.1 on 2024-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0115_remove_salesmancollection_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesmancollectionbill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
