# Generated by Django 5.1.1 on 2024-11-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0116_alter_salesmancollectionbill_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesmancollection",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
