# Generated by Django 5.1.1 on 2024-11-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0119_alter_bankstatement_bank_alter_chequedeposit_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chequedeposit",
            name="bank",
            field=models.CharField(
                choices=[
                    ("SBI", "State Bank of India"),
                    ("KVB", "Karur Vysya Bank"),
                    ("HDFC", "HDFC Bank"),
                    ("ICICI", "ICICI Bank"),
                    ("IB", "Indian Bank"),
                    ("PNB", "Punjab National Bank"),
                    ("BOB", "Bank of Baroda"),
                    ("UBI", "Union Bank of India"),
                    ("CANARA", "Canara Bank"),
                    ("AXIS", "Axis Bank"),
                ],
                max_length=100,
            ),
        ),
    ]
