# Generated by Django 5.1.1 on 2024-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0121_alter_chequedeposit_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chequedeposit",
            name="bank",
            field=models.CharField(
                choices=[
                    ("KVB 650", "KVB 650"),
                    ("SBI", "SBI"),
                    ("CANARA", "CANARA"),
                    ("BARODA", "BARODA"),
                    ("UNION BANK", "UNION BANK"),
                    ("AXIS", "AXIS"),
                    ("HDFC", "HDFC"),
                    ("CENTRAL BANK", "CENTRAL BANK"),
                    ("INDIAN BANK", "INDIAN BANK"),
                    ("IOB", "IOB"),
                    ("ICICI", "ICICI"),
                    ("CUB", "CUB"),
                    ("KOTAK", "KOTAK"),
                    ("SYNDICATE", "SYNDICATE"),
                    ("TMB", "TMB"),
                    ("UNITED BANK", "UNITED BANK"),
                    ("TCB", "TCB"),
                    ("PGB", "PGB"),
                ],
                max_length=100,
            ),
        ),
    ]
