# Generated by Django 5.1.1 on 2024-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0124_pendingsheet_pendingsheetbills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PendingSheetBills",
            new_name="PendingSheetBill",
        ),
    ]
