# Generated by Django 5.1.1 on 2024-12-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0125_rename_pendingsheetbills_pendingsheetbill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingsheetbill",
            old_name="inum",
            new_name="bill",
        ),
    ]
