# Generated by Django 5.1.1 on 2024-12-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0126_rename_inum_pendingsheetbill_bill"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pendingsheetbill",
            unique_together={("sheet", "bill")},
        ),
    ]
