# Generated by Django 5.1.1 on 2024-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0129_bill_delivery_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsheet",
            name="date",
            field=models.DateField(),
        ),
    ]
