# Generated by Django 5.1.1 on 2024-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0130_alter_pendingsheet_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="automatic",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
