# Generated by Django 5.1.1 on 2024-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0131_billing_automatic"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="bounced",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="bank",
            field=models.TextField(
                choices=[
                    ("KVB CA", "KVB CA"),
                    ("SBI CA", "SBI CA"),
                    ("SBI OD", "SBI OD"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pendingsheetbill",
            name="bill_status",
            field=models.TextField(
                choices=[
                    ("scanned", "Scanned"),
                    ("qrcode_not_found", "qrcode_not_found"),
                    ("loading_sheet", "loading_sheet"),
                    ("sales_return", "sales_return"),
                    ("bill_with_shop", "Bill With Shop"),
                    ("others", "Other Reason"),
                ],
                default="scanned",
                max_length=25,
                null=True,
            ),
        ),
    ]
