# Generated by Django 5.1.1 on 2024-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0133_remove_bankstatement_bounced"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="cheque_status",
            field=models.TextField(
                choices=[("passed", "Passed"), ("bounced", "Bounced")], default="passed"
            ),
        ),
    ]
