# Generated by Django 5.1.1 on 2024-12-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0134_bankstatement_cheque_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="type",
            field=models.TextField(
                choices=[
                    ("cheque", "Cheque"),
                    ("neft", "NEFT"),
                    ("upi", "UPI (IKEA)"),
                    ("cash_deposit", "Cash Deposit"),
                    ("others", "Others"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
