# Generated by Django 5.1.1 on 2025-05-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0137_alter_bankstatement_cheque_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesmancollection",
            name="party",
        ),
        migrations.RemoveField(
            model_name="salesmancollectionbill",
            name="chq",
        ),
        migrations.RemoveField(
            model_name="salesmancollectionbill",
            name="inum",
        ),
        migrations.DeleteModel(
            name="BillDelivery",
        ),
        migrations.DeleteModel(
            name="RetailPrint",
        ),
        migrations.DeleteModel(
            name="SalesmanPendingSheetX",
        ),
        migrations.DeleteModel(
            name="TodayBillIn",
        ),
        migrations.DeleteModel(
            name="TodayBillOut",
        ),
        migrations.DeleteModel(
            name="WholeSalePrint",
        ),
        migrations.AlterUniqueTogether(
            name="pendingsheetbill",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="bill",
            name="loading_sheet",
        ),
        migrations.AddField(
            model_name="bill",
            name="loading_sheet_id",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="cheque_status",
            field=models.TextField(
                blank=True,
                choices=[("passed", "Passed"), ("bounced", "Bounced")],
                db_default="passed",
                default="passed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="beat",
            name="salesman_code",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="billingprocessstatus",
            name="billing",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_status",
                to="app.billing",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="SalesmanCollection",
        ),
        migrations.DeleteModel(
            name="SalesmanCollectionBill",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="bill_status",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="days",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="outstanding_amt",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="outstanding_on_bill",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="outstanding_on_ikea",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="outstanding_on_sheet",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="payment_mode",
        ),
        migrations.RemoveField(
            model_name="pendingsheetbill",
            name="sheet",
        ),
        migrations.DeleteModel(
            name="PendingSheet",
        ),
    ]
