# Generated by Django 5.1.1 on 2025-05-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0138_remove_salesmancollection_party_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingSheetBill",
        ),
    ]
