# Generated by Django 5.1.1 on 2025-05-19 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0139_delete_pendingsheetbill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="loading_sheet_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bills",
                to="app.salesmanloadingsheet",
            ),
        ),
    ]
