# Generated by Django 5.1.1 on 2025-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0140_alter_bill_loading_sheet_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adjustment",
            name="id",
        ),
        migrations.AlterField(
            model_name="adjustment",
            name="inum",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
