# Generated by Django 5.1.1 on 2025-05-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0141_remove_adjustment_id_alter_adjustment_inum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="loading_sheet_id",
            new_name="loading_sheet",
        ),
    ]
