# Generated by Django 5.1.1 on 2025-05-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0142_rename_loading_sheet_id_bill_loading_sheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingSheet",
            fields=[
                (
                    "sheet_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("salesman", models.TextField(max_length=30)),
                ("beat", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PendingSheetBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.IntegerField()),
                ("outstanding_amt", models.IntegerField()),
                ("outstanding_on_ikea", models.IntegerField(null=True)),
                ("outstanding_on_bill", models.IntegerField(null=True)),
                ("outstanding_on_sheet", models.IntegerField(null=True)),
                (
                    "payment_mode",
                    models.TextField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("neft", "NEFT"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "bill_status",
                    models.TextField(
                        choices=[
                            ("scanned", "Scanned"),
                            ("qrcode_not_found", "qrcode_not_found"),
                            ("loading_sheet", "loading_sheet"),
                            ("sales_return", "sales_return"),
                            ("bill_with_shop", "Bill With Shop"),
                            ("others", "Other Reason"),
                        ],
                        default="scanned",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.sales",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="app.pendingsheet",
                    ),
                ),
            ],
            options={
                "unique_together": {("sheet", "bill")},
            },
        ),
    ]
